#!/bin/sh

set -e

if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-remove" ]; then

  FILE=/usr/share/icons/gnome/scalable/places/start-here.svg
  [ -e "$FILE" ] && update-alternatives --install "$FILE" start-here.svg /usr/share/icons/Papirus/64x64/apps/distributor-logo.svg 40

  UPDATE_CACHE=
  [ -x /usr/bin/gtk-update-icon-cache-3.0 ] && UPDATE_CACHE=gtk-update-icon-cache-3.0
  [ -x /usr/bin/gtk-update-icon-cache ] && UPDATE_CACHE=gtk-update-icon-cache

  if [ -n "$UPDATE_CACHE" ]; then
    if ! $UPDATE_CACHE --force --quiet /usr/share/icons/Papirus; then
      echo "WARNING: icon cache generation failed"
    fi
  fi

fi
