#!/bin/sh

set -e

if [ "$1" = "remove" ] || [ "$1" = "deconfigure" ]; then
  update-alternatives --remove start-here.svg /usr/share/icons/Papirus/64x64/apps/distributor-logo.svg
  rm -f /usr/share/icons/Papirus/icon-theme.cache
fi
