#!/bin/sh

set -e

if [ "$1" = "remove" ] || [ "$1" = "deconfigure" ]; then
  update-alternatives --remove start-here.svg /usr/share/icons/Faenza/places/scalable/start-here.svg
  rm -f /usr/share/icons/Faenza/icon-theme.cache
fi
